name: Quality check

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  build:
    name: Check code quality.
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Clone the repository.
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Get packages for the Flutter project.
        run: scripts/pub_get_all.sh

      - name: Update the flutter version file.
        run: scripts/update_flutter_version.sh

      - name: Static analysis.
        run: ./flutterw analyze

      - name: Unit tests.
        run: ./flutterw test
